### ISSUE TITLE
 Issue with Focus Ring Color not Matching Theme

### ISSUE THREAD

**Issue by dicaccamovincenzo92** [primefaces/primevue-tailwind#144]
Hello,

I'm currently utilizing tailwind.primevue in a Laravel-based project, which incorporates Jetstream with Vue 3, Inertia and Vite. The library integrates well overall, but I've encountered an issue related to the focus ring color.

When elements such as input texts or buttons are focused, the ring color defaults to blue, which is the standard for Tailwind. However, it does not adapt to the theme colors set in my project. Specifically, I'm using the "Lara Dark Amber" and "Lara Green Light" themes, but this issue persists.

I've attached screenshots to illustrate the problem:
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/fb601a7b-509c-43a7-ba7a-7ee2283497f6)
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/6692e5fe-0f1c-4b0a-b2c7-6889df513e44)

Could you please provide guidance on how to ensure the focus ring color aligns with the set theme colors? Any help or suggestions would be greatly appreciated.

Thank you for your assistance.

**Comment by zejji** [comment]
I've also run into this problem. I think it is caused by the fact that Tailwind does not generate opacity variants for ring classes, e.g. `ring-primary-xxx/xx`, `focus:ring-primary-xxx/xx`, `focus:ring-primary-xxx/xx` etc.

I have only been able to get round it by adding the missing classes which tailwind does not generate in my main.css file e.g.:

``` css
.focus\:ring-primary-300\/50:focus {
  --tw-ring-color: hsla(
    var(--primary-hue),
    calc(72% * var(--primary-saturation-multiplier)),
    calc(67% * var(--primary-lightness-multiplier)),
    0.5
  );
}

.focus\:ring-primary-400\/50:focus {
  --tw-ring-color: hsla(
    var(--primary-hue),
    calc(64% * var(--primary-saturation-multiplier)),
    calc(52% * var(--primary-lightness-multiplier)),
    0.5
  );
}

.focus\:ring-primary-500\/50:focus {
  --tw-ring-color: hsla(
    var(--primary-hue),
    calc(84% * var(--primary-saturation-multiplier)),
    calc(39% * var(--primary-lightness-multiplier)),
    0.5
  );
}

.ring-primary-300\/50 {
  --tw-ring-color: hsla(
    var(--primary-hue),
    calc(72% * var(--primary-saturation-multiplier)),
    calc(67% * var(--primary-lightness-multiplier)),
    0.5
  );
}

.ring-primary-400\/50 {
  --tw-ring-color: hsla(
    var(--primary-hue),
    calc(64% * var(--primary-saturation-multiplier)),
    calc(52% * var(--primary-lightness-multiplier)),
    0.5
  );
}

.ring-primary-500\/50 {
  --tw-ring-color: hsla(
    var(--primary-hue),
    calc(84% * var(--primary-saturation-multiplier)),
    calc(39% * var(--primary-lightness-multiplier)),
    0.5
  );
}
```
