### ISSUE TITLE
p-inputtext losing border-primary in dark mode

### ISSUE THREAD

**Issue by frankchen211** [primefaces/primevue-tailwind#370]
`dark:enabled:focus:border-primary` is missing in style `.p-inputtext`

``` css
.p-inputtext {
    @apply appearance-none rounded-md
        border border-surface-300 dark:border-surface-700 
        enabled:hover:border-surface-400 dark:enabled:hover:border-surface-600
        enabled:focus:border-primary
        bg-surface-0 dark:bg-surface-950
        text-surface-700 dark:text-surface-0
        disabled:bg-surface-200 disabled:text-surface-500 dark:disabled:bg-surface-700 dark:disabled:text-surface-400 disabled:opacity-100
        placeholder:text-surface-500 dark:placeholder:text-surface-400
        px-3 py-2
        transition-colors duration-200
        shadow-[0_1px_2px_0_rgba(18,18,23,0.05)]
        outline-none
}
```
